/**
 * Le registre chat, pour les 26 langues latines du produit.
 *
 * Test-only module, comme `langCorpus.ts`, et le meme garde statique l'empeche
 * d'entrer dans le bundle livre.
 *
 * POURQUOI IL EXISTE. Tatoeba est de la phrase ecrite complete. Le produit tourne
 * sur des lignes de chat de cinq mots, en minuscules, sans ponctuation. Tout ce
 * que `langMatrix.test.ts` mesure porte donc a cote du regime reel, et le trou
 * est le plus grand exactement la ou il fait le plus mal : les 26 langues qui
 * s'ecrivent en alphabet latin, que le pre-controle d'ecriture ne sert pas du
 * tout et qui n'ont que franc et le lexique de mots courts pour elles.
 *
 * CE QU'IL VAUT ET CE QU'IL NE VAUT PAS, a lire avant d'en citer un chiffre.
 *
 * Il est ECRIT PAR CE PROJET, donc ajustable par lui, et c'est exactement ce que
 * `langCorpus.ts` n'est pas. Un chiffre de rappel mesure ici le vocabulaire
 * choisi par celui qui a ecrit les lignes autant que le detecteur. Il ne prouve
 * donc PAS qu'une regle marche ; il sert a trois choses qui, elles, tiennent :
 *
 *   1. Le taux de SILENCE, qui ne depend pas de savoir si la reponse est juste.
 *      C'est le chiffre qui decide du routage vers le moteur on-device.
 *   2. La PROTECTION contre les regressions : une ligne qui marchait et qui
 *      cesse de marcher est un fait, quelle que soit l'origine de la ligne.
 *   3. Le contraste avec Tatoeba sur les MEMES langues, qui dit combien le
 *      registre change la reponse.
 *
 * Precedent qui a motive tout ca : `langDetect.dix.test.ts` fait la meme chose a
 * la main pour les cinq langues non latines et a attrape une regression que les
 * 5040 lignes de Tatoeba n'avaient pas vue, parce que le russe de chat n'ecrit
 * presque jamais ы, э ou ё.
 *
 * LES DIACRITIQUES SONT ECRITS, ET C'EST UNE DECISION.
 *
 * Un chat reel contient les deux : des gens qui tapent `sie` pour `się` et
 * `cok` pour `çok`, et des gens qui tapent tout. Ecrire le corpus sans
 * diacritiques l'aurait biaise CONTRE les regles de lettres exclusives, qui
 * n'ont plus rien a lire ; l'ecrire avec le biaise en leur faveur.
 *
 * Il est donc ecrit comme la langue s'ecrit, et `langChat.test.ts` le mesure
 * DEUX FOIS, tel quel et diacritiques retirees. Les deux chiffres encadrent le
 * reel au lieu de choisir un camp, et l'ecart entre eux est la vraie mesure de
 * ce que le clavier coute a la detection. C'est une question produit a part
 * entiere : elle dit ce qui arrive aux 26 langues latines quand l'utilisateur
 * tape vite.
 *
 * DISCIPLINE. Les 390 lignes ont ete ecrites d'un bloc AVANT toute mesure et
 * avant toute regle qui pourrait en profiter. Comme pour Tatoeba, l'usage prevu
 * est de regler sur les indices pairs et de valider sur les impairs.
 *
 * Contenu : reactions, questions, salutations, plaintes techniques, banter. Pas
 * de nom de chaine ni de streamer, jamais. Pas d'emoji : la dilution par emoji
 * est deja couverte par `langDetect.test.ts` et melanger les deux sujets rendrait
 * les deux illisibles.
 *
 * `pt-br` est absent pour la meme raison que dans `langCorpus.ts` : la
 * distinction avec `pt` est lexicale et fine, et une ligne de chat de cinq mots
 * est le pire endroit pour la trancher.
 */
export const LANG_CHAT: Record<string, string[]> = {
  en: [
    'that was insane',
    'no way he did that',
    'chat is going crazy',
    'first time here',
    'what happened',
    'turn the music down',
    'who else is watching',
    'i cant believe it',
    'so close',
    'he is so bad at this',
    'anyone from uk',
    'stream is lagging',
    'how long has he been live',
    'he is cracked today',
    'same thing every time',
  ],
  fr: [
    "c'est n'importe quoi",
    'il est trop fort',
    'quelqu’un sait ce qui se passe',
    'je viens d’arriver',
    'le son est trop bas',
    'vas-y fonce',
    'trop drôle',
    'il joue mal là',
    'ça marche pas chez moi',
    'il va gagner',
    "c'est pas possible",
    'première fois que je regarde',
    'monte le son',
    'on est combien',
    'encore la même chose',
  ],
  es: [
    'qué está pasando aquí',
    'no puede ser',
    'juega fatal hoy',
    'alguien de españa',
    'sube el volumen',
    'vamos que se puede',
    'me acabo de conectar',
    'esto es increíble',
    'se cortó el stream',
    'qué risa',
    'otra vez lo mismo',
    'no me lo creo',
    'está jugando muy bien',
    'cuánto falta',
    'se le da fatal',
  ],
  pt: [
    'que isso mano',
    'alguém do brasil',
    'tá muito bom hoje',
    'aumenta o som',
    'não acredito nisso',
    'acabei de chegar',
    'ele joga muito',
    'vai dar certo',
    'tá travando aqui',
    'que jogada',
    'primeira vez assistindo',
    'ele é muito ruim',
    'quanto tempo falta',
    'melhor live de hoje',
    'não deu pra ver',
  ],
  de: [
    'das ist doch nicht möglich',
    'wer schaut noch zu',
    'mach die musik leiser',
    'er spielt richtig gut',
    'bin gerade erst gekommen',
    'das war knapp',
    'kann jemand helfen',
    'der stream ruckelt',
    'so ein pech',
    'das glaub ich nicht',
    'einfach nur krass',
    'wie lange noch',
    'er hat keine chance',
    'wieder das gleiche',
    'jemand aus deutschland hier',
  ],
  it: [
    'ma che sta facendo',
    'qualcuno dall’italia',
    'alza il volume',
    'sta giocando benissimo',
    'appena arrivato',
    'non ci credo',
    'che sfortuna',
    'lo stream si blocca',
    'quanto manca',
    'è troppo forte',
    'prima volta qui',
    'sempre la stessa cosa',
    'andiamo così',
    'non si vede niente',
    'gioca malissimo oggi',
  ],
  nl: [
    'wat gebeurt er nou',
    'iemand uit nederland',
    'zet het geluid harder',
    'hij speelt echt goed',
    'net binnengekomen',
    'dat kan niet waar zijn',
    'de stream hapert',
    'hoe lang nog',
    'gewoon niet te geloven',
    'hij heeft geen kans',
    'weer hetzelfde',
    'dat was close',
    'eerste keer hier',
    'ik zie niks',
    'hij speelt echt slecht vandaag',
  ],
  pl: [
    'co tu się dzieje',
    'ktoś z polski',
    'podgłoś trochę',
    'gra świetnie dzisiaj',
    'dopiero wszedłem',
    'nie wierzę w to',
    'stream się tnie',
    'ile jeszcze',
    'ale pech',
    'znowu to samo',
    'on nie ma szans',
    'pierwszy raz tutaj',
    'nic nie widać',
    'dawaj dawaj',
    'słabo gra dzisiaj',
  ],
  sv: [
    'vad händer här',
    'någon från sverige',
    'höj ljudet',
    'han spelar riktigt bra',
    'kom precis hit',
    'det är inte sant',
    'streamen hackar',
    'hur länge till',
    'vilken otur',
    'samma sak igen',
    'han har ingen chans',
    'första gången här',
    'jag ser ingenting',
    'kör på nu',
    'spelar dåligt idag',
  ],
  cs: [
    'co se to děje',
    'někdo z čech',
    'přidej zvuk',
    'hraje dneska skvěle',
    'právě jsem přišel',
    'tomu nevěřím',
    'stream seká',
    'jak dlouho ještě',
    'to je smůla',
    'zase to samé',
    'nemá šanci',
    'poprvé tady',
    'nic nevidím',
    'do toho',
    'hraje hrozně dnes',
  ],
  sk: [
    'čo sa to deje',
    'niekto zo slovenska',
    'pridaj zvuk',
    'dnes hrá výborne',
    'práve som prišiel',
    'tomu neverím',
    'stream sa seká',
    'ako dlho ešte',
    'to je smola',
    'zase to isté',
    'nemá šancu',
    'prvýkrát tu',
    'nič nevidím',
    'do toho ideme',
    'hrá hrozne dnes',
  ],
  ro: [
    'ce se întâmplă aici',
    'cineva din românia',
    'dă mai tare',
    'joacă foarte bine azi',
    'tocmai am intrat',
    'nu pot să cred',
    'stream ul se blochează',
    'cât mai durează',
    'ce ghinion',
    'iar aceeași treabă',
    'nu are nicio șansă',
    'prima dată aici',
    'nu văd nimic',
    'hai că poate',
    'joacă groaznic azi',
  ],
  tr: [
    'burada ne oluyor',
    'türkiye’den kimse var mı',
    'sesi aç biraz',
    'bugün çok iyi oynuyor',
    'yeni geldim',
    'buna inanamıyorum',
    'yayın donuyor',
    'daha ne kadar var',
    'ne şanssızlık',
    'yine aynı şey',
    'hiç şansı yok',
    'ilk defa buradayım',
    'hiçbir şey görmüyorum',
    'hadi bakalım',
    'berbat oynuyor bugün',
  ],
  vi: [
    'đang xảy ra chuyện gì vậy',
    'có ai ở việt nam không',
    'tăng âm lượng lên',
    'hôm nay chơi hay quá',
    'mới vào thôi',
    'không thể tin được',
    'stream bị giật',
    'còn bao lâu nữa',
    'xui quá',
    'lại như cũ',
    'không có cơ hội đâu',
    'lần đầu xem',
    'không thấy gì cả',
    'cố lên',
    'chơi tệ quá hôm nay',
  ],
  id: [
    'ada apa nih',
    'ada yang dari indonesia',
    'suaranya dikencengin dong',
    'main bagus banget hari ini',
    'baru masuk',
    'gak percaya gue',
    'streamnya patah patah',
    'berapa lama lagi',
    'sial banget',
    'gitu lagi gitu lagi',
    'gak ada kesempatan',
    'pertama kali nonton',
    'gak keliatan apa apa',
    'ayo bisa',
    'mainnya jelek banget',
  ],
  ms: [
    'apa yang berlaku ni',
    'ada orang malaysia tak',
    'besarkan bunyi sikit',
    'main bagus hari ini',
    'baru sahaja masuk',
    'tak percaya aku',
    'stream tersekat sekat',
    'berapa lama lagi',
    'malang betul',
    'sama je macam tadi',
    'tiada peluang langsung',
    'kali pertama tengok',
    'tak nampak apa apa',
    'boleh punya',
    'main teruk hari ini',
  ],
  fi: [
    'mitä täällä tapahtuu',
    'onko ketään suomesta',
    'laita ääntä kovemmalle',
    'pelaa tosi hyvin tänään',
    'tulin just',
    'en voi uskoa tätä',
    'striimi pätkii',
    'kauanko vielä',
    'mikä huono tuuri',
    'taas sama juttu',
    'ei ole mitään mahdollisuuksia',
    'eka kerta täällä',
    'en näe mitään',
    'anna mennä',
    'pelaa surkeasti tänään',
  ],
  no: [
    'hva skjer her',
    'noen fra norge',
    'skru opp lyden',
    'han spiller veldig bra i dag',
    'kom nettopp',
    'jeg tror det ikke',
    'strømmen hakker',
    'hvor lenge til',
    'for en uflaks',
    'samme greia igjen',
    'han har ingen sjanse',
    'første gang her',
    'jeg ser ingenting',
    'kom igjen da',
    'spiller dårlig i dag',
  ],
  da: [
    'hvad sker der her',
    'er der nogen fra danmark',
    'skru op for lyden',
    'han spiller rigtig godt i dag',
    'jeg kom lige',
    'det kan jeg ikke tro',
    'streamen hakker',
    'hvor lang tid endnu',
    'sikke noget uheld',
    'det samme igen',
    'han har ingen chance',
    'første gang her',
    'jeg kan ikke se noget',
    'kom nu',
    'spiller elendigt i dag',
  ],
  hu: [
    'mi folyik itt',
    'van itt valaki magyarországról',
    'tekerd fel a hangot',
    'ma nagyon jól játszik',
    'most jöttem',
    'ezt nem hiszem el',
    'akadozik az adás',
    'mennyi van még',
    'micsoda balszerencse',
    'megint ugyanaz',
    'esélye sincs',
    'először vagyok itt',
    'nem látok semmit',
    'gyerünk',
    'borzalmasan játszik ma',
  ],
  ca: [
    'què està passant aquí',
    'hi ha algú de catalunya',
    'puja el volum',
    'avui juga molt bé',
    'acabo d’arribar',
    'no m’ho puc creure',
    'l’emissió es talla',
    'quant queda',
    'quina mala sort',
    'un altre cop el mateix',
    'no té cap oportunitat',
    'primer cop aquí',
    'no veig res',
    'va que sí',
    'juga fatal avui',
  ],
  sl: [
    'kaj se dogaja tukaj',
    'je kdo iz slovenije',
    'povečaj glasnost',
    'danes igra zelo dobro',
    'pravkar sem prišel',
    'tega ne morem verjeti',
    'prenos se zatika',
    'koliko še',
    'kakšna smola',
    'spet isto',
    'nima nobenih možnosti',
    'prvič sem tukaj',
    'ničesar ne vidim',
    'dajmo',
    'grozno igra danes',
  ],
  et: [
    'mis siin toimub',
    'kas keegi on eestist',
    'keera heli valjemaks',
    'mängib täna väga hästi',
    'tulin just',
    'ma ei suuda uskuda',
    'voog hakib',
    'kui kaua veel',
    'milline ebaõnn',
    'jälle sama asi',
    'tal pole mingit võimalust',
    'esimest korda siin',
    'ma ei näe midagi',
    'lähme',
    'mängib täna kohutavalt',
  ],
  lt: [
    'kas čia vyksta',
    'ar yra kas nors iš lietuvos',
    'pagarsink',
    'šiandien labai gerai žaidžia',
    'ką tik atėjau',
    'negaliu patikėti',
    'transliacija stringa',
    'kiek dar liko',
    'kokia nesėkmė',
    'vėl tas pats',
    'neturi jokių šansų',
    'pirmą kartą čia',
    'nieko nematau',
    'pirmyn',
    'šiandien baisiai žaidžia',
  ],
  lv: [
    'kas te notiek',
    'vai kāds ir no latvijas',
    'pagriez skaļāk',
    'šodien spēlē ļoti labi',
    'tikko atnācu',
    'nespēju noticēt',
    'straume ķeras',
    'cik ilgi vēl',
    'kāda neveiksme',
    'atkal tas pats',
    'viņam nav nekādu izredžu',
    'pirmo reizi šeit',
    'neko neredzu',
    'uz priekšu',
    'šodien šausmīgi spēlē',
  ],
  tl: [
    'ano ba ang nangyayari dito',
    'may taga pilipinas ba',
    'lakasan mo ang tunog',
    'ang galing niya maglaro ngayon',
    'kakapasok ko lang',
    'hindi ako makapaniwala',
    'nag lalag ang stream',
    'gaano pa katagal',
    'ang malas naman',
    'ganun na naman',
    'wala siyang panama',
    'first time ko dito',
    'wala akong makita',
    'kaya mo yan',
    'ang pangit maglaro ngayon',
  ],
};
