/**
 * Le second corpus de chat, et il est SEPARE du premier exprès.
 *
 * Test-only module, comme les trois autres corpus, meme garde statique.
 *
 * POURQUOI IL N'EST PAS FUSIONNE AVEC `langChatCorpus.ts`. Le premier corpus a
 * ete ecrit avant que le lexique ne soit etendu, et le lexique a ensuite grossi
 * de plus de deux cents entrees en regardant ses lignes muettes. Il n'est donc
 * plus un banc independant pour ce lexique : il en est en partie la source, et
 * un chiffre de rappel mesure dessus flatte forcement.
 *
 * Ces 260 lignes ont ete ecrites APRES, sans regarder une seule fois ce que le
 * detecteur en dit, et sur d'autres sujets : abonnements, horaires, connexion,
 * demandes de clip, reactions a une action ratee. Elles constituent un
 * HOLD-OUT AVEUGLE pour tout ce qui a ete ajoute jusqu'ici.
 *
 * Fusionner les deux fichiers detruirait cette propriete, et elle ne peut pas
 * etre reconstruite : une fois qu'on a lu ce que le detecteur fait d'une ligne,
 * elle cesse d'etre aveugle. C'est pour ca que le fichier reste a part et que
 * son en-tete le dit avant d'en citer un chiffre.
 *
 * COMMENT S'EN SERVIR, et comment ne pas le griller :
 *   - mesurer dessus AVANT de toucher au lexique, pour savoir ou on part ;
 *   - ne JAMAIS y prendre un mot a ajouter au lexique. Le jour ou on le fait,
 *     ce corpus devient le premier et il en faut un troisieme ;
 *   - si le rappel y est nettement inferieur a celui du premier corpus, l'ecart
 *     est la part de memorisation du lexique, et c'est exactement le chiffre
 *     qu'on veut connaitre.
 *
 * Memes conventions que le premier : 26 langues latines, diacritiques ecrits,
 * pas d'emoji, pas de nom de chaine ni de streamer, `pt-br` absent.
 */
export const LANG_CHAT2: Record<string, readonly string[]> = {
  en: [
    'did he just do that',
    'someone clip that',
    'the game looks broken',
    'i was here yesterday too',
    'best play of the week',
    'he needs to slow down',
    'nobody saw that coming',
    'when does he go live',
    'my internet is terrible',
    'thanks for the sub',
  ],
  fr: [
    'il vient de faire quoi là',
    'quelqu’un a clippé ça',
    'le jeu a l’air cassé',
    'j’étais là hier aussi',
    'la meilleure action de la semaine',
    'il doit ralentir un peu',
    'personne n’a vu venir ça',
    'il commence à quelle heure',
    'ma connexion est horrible',
    'merci pour l’abonnement',
  ],
  es: [
    'acaba de hacer eso',
    'que alguien lo grabe',
    'el juego parece roto',
    'ayer también estuve aquí',
    'la mejor jugada de la semana',
    'tiene que ir más despacio',
    'nadie se lo esperaba',
    'a qué hora empieza',
    'mi conexión va fatal',
    'gracias por la suscripción',
  ],
  pt: [
    'ele acabou de fazer isso',
    'alguém corta esse trecho',
    'o jogo parece quebrado',
    'ontem eu também estava aqui',
    'melhor jogada da semana',
    'ele precisa ir mais devagar',
    'ninguém esperava por essa',
    'que horas ele começa',
    'minha internet está horrível',
    'obrigado pela inscrição',
  ],
  de: [
    'hat er das gerade wirklich gemacht',
    'kann das jemand clippen',
    'das spiel wirkt kaputt',
    'gestern war ich auch hier',
    'beste aktion der woche',
    'er muss langsamer machen',
    'damit hat keiner gerechnet',
    'wann fängt er an',
    'meine leitung ist furchtbar',
    'danke für das abo',
  ],
  it: [
    'ha appena fatto quello',
    'qualcuno lo registri',
    'il gioco sembra rotto',
    'ieri ero qui anch’io',
    'la giocata della settimana',
    'deve andare più piano',
    'nessuno se lo aspettava',
    'a che ora comincia',
    'la mia connessione fa schifo',
    'grazie per l’abbonamento',
  ],
  nl: [
    'heeft hij dat net gedaan',
    'kan iemand dat knippen',
    'het spel lijkt kapot',
    'gisteren was ik er ook',
    'beste actie van de week',
    'hij moet rustiger doen',
    'niemand zag dat aankomen',
    'hoe laat begint hij',
    'mijn verbinding is waardeloos',
    'bedankt voor het abonnement',
  ],
  pl: [
    'czy on to właśnie zrobił',
    'niech ktoś to nagra',
    'gra wygląda na zepsutą',
    'wczoraj też tu byłem',
    'najlepsza akcja tygodnia',
    'musi trochę zwolnić',
    'nikt się tego nie spodziewał',
    'o której zaczyna',
    'moje łącze jest fatalne',
    'dzięki za suba',
  ],
  sv: [
    'gjorde han verkligen det',
    'någon klippa det där',
    'spelet verkar trasigt',
    'jag var här igår också',
    'veckans bästa spel',
    'han måste sakta ner',
    'ingen såg det komma',
    'när börjar han',
    'min uppkoppling är hemsk',
    'tack för prenumerationen',
  ],
  cs: [
    'fakt to právě udělal',
    'může to někdo střihnout',
    'hra vypadá rozbitě',
    'včera jsem tu byl taky',
    'nejlepší akce týdne',
    'musí trochu zpomalit',
    'to nikdo nečekal',
    'v kolik začíná',
    'moje připojení je hrozné',
    'díky za předplatné',
  ],
  sk: [
    'naozaj to práve spravil',
    'môže to niekto zostrihať',
    'hra vyzerá pokazená',
    'včera som tu bol tiež',
    'najlepšia akcia týždňa',
    'musí trochu spomaliť',
    'to nikto nečakal',
    'o koľkej začína',
    'moje pripojenie je hrozné',
    'vďaka za predplatné',
  ],
  ro: [
    'chiar a făcut asta acum',
    'poate cineva să taie clipul',
    'jocul pare stricat',
    'ieri am fost și eu aici',
    'cea mai bună fază a săptămânii',
    'trebuie să încetinească',
    'nimeni nu se aștepta',
    'la ce oră începe',
    'conexiunea mea e groaznică',
    'mulțumesc pentru abonament',
  ],
  tr: [
    'bunu gerçekten şimdi mi yaptı',
    'biri bunu kessin',
    'oyun bozuk görünüyor',
    'dün de buradaydım',
    'haftanın en iyi hareketi',
    'biraz yavaşlaması lazım',
    'bunu kimse beklemiyordu',
    'saat kaçta başlıyor',
    'benim bağlantım berbat',
    'abonelik için teşekkürler',
  ],
  vi: [
    'anh ấy vừa làm thế thật à',
    'ai đó cắt đoạn này đi',
    'game trông như bị lỗi',
    'hôm qua tôi cũng ở đây',
    'pha hay nhất tuần',
    'anh ấy cần chậm lại',
    'không ai ngờ được',
    'mấy giờ bắt đầu vậy',
    'mạng của tôi tệ lắm',
    'cảm ơn vì đã đăng ký',
  ],
  id: [
    'dia baru saja ngelakuin itu',
    'ada yang potong klipnya dong',
    'gamenya kayak rusak',
    'kemarin aku juga di sini',
    'permainan terbaik minggu ini',
    'dia harus pelan pelan',
    'nggak ada yang nyangka',
    'jam berapa mulainya',
    'koneksi gue jelek banget',
    'makasih udah subscribe',
  ],
  ms: [
    'dia baru sahaja buat itu',
    'ada sesiapa boleh potong klip',
    'permainan nampak rosak',
    'semalam saya pun ada di sini',
    'aksi terbaik minggu ini',
    'dia kena perlahan sikit',
    'tiada siapa jangka',
    'pukul berapa dia mula',
    'sambungan saya teruk',
    'terima kasih kerana melanggan',
  ],
  fi: [
    'tekikö hän tuon oikeasti',
    'joku leikkaa tuosta klippi',
    'peli näyttää rikkinäiseltä',
    'olin täällä eilenkin',
    'viikon paras suoritus',
    'hänen pitää hidastaa',
    'kukaan ei osannut odottaa',
    'mihin aikaan hän aloittaa',
    'minun yhteyteni on surkea',
    'kiitos tilauksesta',
  ],
  no: [
    'gjorde han virkelig det nå',
    'noen må klippe det der',
    'spillet ser ødelagt ut',
    'jeg var her i går også',
    'ukens beste spill',
    'han må roe seg litt',
    'ingen så det komme',
    'når begynner han',
    'nettet mitt er forferdelig',
    'takk for abonnementet',
  ],
  da: [
    'gjorde han virkelig det nu',
    'nogen må klippe det der',
    'spillet ser ødelagt ud',
    'jeg var her i går også',
    'ugens bedste spil',
    'han skal lige falde ned',
    'ingen så det komme',
    'hvornår begynder han',
    'min forbindelse er forfærdelig',
    'tak for abonnementet',
  ],
  hu: [
    'tényleg most csinálta ezt',
    'valaki vágja ki ezt a részt',
    'a játék töröttnek tűnik',
    'tegnap is itt voltam',
    'a hét legjobb húzása',
    'lassítania kellene kicsit',
    'erre senki nem számított',
    'hánykor kezd',
    'az én netem borzalmas',
    'köszönöm az előfizetést',
  ],
  ca: [
    'ho acaba de fer de debò',
    'algú que ho retalli',
    'el joc sembla trencat',
    'ahir també hi era',
    'la millor jugada de la setmana',
    'ha d’anar més a poc a poc',
    'ningú s’ho esperava',
    'a quina hora comença',
    'la meva connexió va fatal',
    'gràcies per la subscripció',
  ],
  sl: [
    'je to res pravkar naredil',
    'naj kdo to posname',
    'igra izgleda pokvarjena',
    'včeraj sem bil tudi tukaj',
    'najboljša poteza tedna',
    'malo mora upočasniti',
    'tega nihče ni pričakoval',
    'ob kateri uri začne',
    'moja povezava je grozna',
    'hvala za naročnino',
  ],
  et: [
    'kas ta tegi seda tõesti',
    'keegi lõikaks selle välja',
    'mäng tundub katki',
    'eile olin ka siin',
    'nädala parim käik',
    'ta peaks natuke aeglustama',
    'keegi ei osanud oodata',
    'mis kell ta alustab',
    'minu ühendus on kohutav',
    'aitäh tellimuse eest',
  ],
  lt: [
    'ar jis tikrai ką tik tai padarė',
    'kas nors iškirpkite tai',
    'žaidimas atrodo sugedęs',
    'vakar irgi čia buvau',
    'savaitės geriausias ėjimas',
    'jam reikia sulėtinti',
    'niekas to nesitikėjo',
    'kelintą valandą pradeda',
    'mano ryšys siaubingas',
    'ačiū už prenumeratą',
  ],
  lv: [
    'vai viņš tiešām to tikko izdarīja',
    'kāds izgrieziet šo',
    'spēle izskatās salauzta',
    'vakar arī biju šeit',
    'nedēļas labākais gājiens',
    'viņam vajag palēnināt',
    'neviens to negaidīja',
    'cikos viņš sāk',
    'mans savienojums ir briesmīgs',
    'paldies par abonementu',
  ],
  tl: [
    'ginawa ba talaga niya yun',
    'may makakapag clip ba niyan',
    'mukhang sira ang laro',
    'kahapon nandito rin ako',
    'pinakamagandang laro ng linggo',
    'kailangan niyang bumagal',
    'walang nakaasa doon',
    'anong oras siya magsisimula',
    'ang bagal ng internet ko',
    'salamat sa subscribe',
  ],
};
