/**
 * Le troisieme corpus de chat, celui sur lequel on a le DROIT de regler.
 *
 * Test-only module, comme les quatre autres corpus, meme garde statique.
 *
 * POURQUOI IL EXISTE, et c'est une question de droits d'usage plus que de
 * donnees. A la fin de la passe precedente il n'y avait plus aucun corpus de
 * chat sur lequel choisir un mot de lexique soit honnete :
 *
 *   `langChatCorpus.ts`   a servi a choisir, donc il ne mesure plus.
 *   `langChatCorpus2.ts`  est AVEUGLE et doit le rester, donc il ne sert qu'a
 *                         mesurer, jamais a choisir.
 *
 * Sans un troisieme, tout travail de lexique supplementaire etait soit aveugle,
 * soit une tricherie. Celui-ci est le corpus de REGLAGE : on lit ses lignes
 * muettes, on y choisit des mots, on mesure le resultat sur le deuxieme.
 *
 * REGLE DES TROIS CORPUS, a garder :
 *   1 regler sur celui-ci ;
 *   2 mesurer sur le deuxieme, en TOTAL seulement, sans jamais lire ses lignes ;
 *   3 le premier reste un banc de non-regression, ses chiffres ne valent plus
 *     comme mesure de rappel.
 *
 * Le jour ou le deuxieme est lu ligne a ligne, il rejoint le premier et il en
 * faut un quatrieme. Une propriete d'aveuglement ne se repare pas.
 *
 * Sujets differents des deux autres exprès, pour que les trois ne soient pas
 * trois echantillons du meme vocabulaire : moderation, emotes, musique, camera,
 * meteo, repas, au revoir. Memes conventions : 26 langues latines, diacritiques
 * ecrits, pas d'emoji, pas de nom de chaine ni de streamer.
 */
export const LANG_CHAT3: Record<string, readonly string[]> = {
  en: [
    'the mods are asleep again',
    'turn on the predictions',
    'this song is a banger',
    'your camera is blurry',
    'how many people are here',
    'i am eating dinner right now',
    'it is raining outside',
    'see you tomorrow everyone',
    'he is finally back',
    'that emote is perfect',
  ],
  fr: [
    'les modos dorment encore',
    'lance les prédictions',
    'cette musique est excellente',
    'ta caméra est floue',
    'on est combien ce soir',
    'je mange en même temps',
    'il pleut dehors ici',
    'à demain tout le monde',
    'il est enfin de retour',
    'cet emote est parfait',
  ],
  es: [
    'los mods están dormidos otra vez',
    'abre las predicciones',
    'esta canción es buenísima',
    'tu cámara se ve borrosa',
    'cuánta gente hay ahora',
    'estoy cenando mientras veo',
    'está lloviendo por aquí',
    'hasta mañana a todos',
    'por fin ha vuelto',
    'ese emote es perfecto',
  ],
  pt: [
    'os mods estão dormindo de novo',
    'abre as previsões',
    'essa música é muito boa',
    'tua câmera está desfocada',
    'quantas pessoas tem aqui',
    'estou jantando enquanto assisto',
    'está chovendo aqui fora',
    'até amanhã pessoal',
    'ele finalmente voltou',
    'esse emote é perfeito',
  ],
  de: [
    'die mods schlafen schon wieder',
    'mach die vorhersagen an',
    'dieses lied ist richtig gut',
    'deine kamera ist unscharf',
    'wie viele leute sind hier',
    'ich esse gerade zu abend',
    'hier draußen regnet es',
    'bis morgen zusammen',
    'er ist endlich zurück',
    'dieses emote ist perfekt',
  ],
  it: [
    'i mod dormono di nuovo',
    'apri le previsioni',
    'questa canzone è bellissima',
    'la tua webcam è sfocata',
    'quante persone ci sono',
    'sto cenando mentre guardo',
    'qui fuori sta piovendo',
    'a domani a tutti',
    'è finalmente tornato',
    'quella emote è perfetta',
  ],
  nl: [
    'de mods slapen weer',
    'zet de voorspellingen aan',
    'dit nummer is echt goed',
    'je camera is wazig',
    'hoeveel mensen zijn er',
    'ik zit te eten intussen',
    'het regent hier buiten',
    'tot morgen allemaal',
    'hij is eindelijk terug',
    'die emote is perfect',
  ],
  pl: [
    'moderatorzy znowu śpią',
    'włącz przewidywania',
    'ta piosenka jest świetna',
    'twoja kamera jest rozmyta',
    'ile osób tu jest',
    'jem kolację przy okazji',
    'na zewnątrz pada deszcz',
    'do jutra wszystkim',
    'w końcu wrócił',
    'ten emote jest idealny',
  ],
  sv: [
    'moderatorerna sover igen',
    'sätt på förutsägelserna',
    'den här låten är grym',
    'din kamera är suddig',
    'hur många är här nu',
    'jag äter middag samtidigt',
    'det regnar här ute',
    'vi ses imorgon allihopa',
    'han är äntligen tillbaka',
    'den emoten är perfekt',
  ],
  cs: [
    'moderátoři zase spí',
    'zapni předpovědi',
    'tahle písnička je super',
    'tvoje kamera je rozmazaná',
    'kolik nás tu je',
    'zrovna večeřím u toho',
    'venku tady prší',
    'zítra na viděnou všem',
    'konečně je zpátky',
    'ten emote je dokonalý',
  ],
  sk: [
    'moderátori zase spia',
    'zapni predpovede',
    'táto pesnička je super',
    'tvoja kamera je rozmazaná',
    'koľko nás tu je',
    'práve večeriam pri tom',
    'vonku tu prší',
    'zajtra dovidenia všetkým',
    'konečne je späť',
    'ten emote je dokonalý',
  ],
  ro: [
    'moderatorii dorm iar',
    'pornește predicțiile',
    'melodia asta e foarte bună',
    'camera ta e neclară',
    'câți oameni sunt aici',
    'mănânc cina între timp',
    'afară plouă aici',
    'pe mâine tuturor',
    'în sfârșit s’a întors',
    'emoticonul ăla e perfect',
  ],
  tr: [
    'moderatörler yine uyuyor',
    'tahminleri aç',
    'bu şarkı çok iyi',
    'kameran bulanık görünüyor',
    'burada kaç kişi var',
    'bu arada akşam yemeği yiyorum',
    'burada dışarıda yağmur yağıyor',
    'yarın görüşürüz herkese',
    'sonunda geri döndü',
    'o emote mükemmel',
  ],
  vi: [
    'mod lại ngủ rồi',
    'mở dự đoán lên đi',
    'bài này hay quá',
    'cam của bạn bị mờ',
    'có bao nhiêu người ở đây',
    'tôi đang ăn tối luôn',
    'ngoài này đang mưa',
    'hẹn gặp lại ngày mai',
    'cuối cùng anh ấy cũng về',
    'cái emote đó chuẩn',
  ],
  id: [
    'modnya tidur lagi',
    'nyalain prediksinya dong',
    'lagu ini enak banget',
    'kamera lo burem',
    'ada berapa orang di sini',
    'gue lagi makan malam',
    'di sini lagi hujan',
    'sampai besok semuanya',
    'akhirnya dia balik',
    'emote itu pas banget',
  ],
  ms: [
    'mod tidur lagi',
    'buka ramalan tu',
    'lagu ni sedap betul',
    'kamera awak kabur',
    'ada berapa orang di sini',
    'saya tengah makan malam',
    'di sini hujan turun',
    'jumpa esok semua',
    'akhirnya dia balik',
    'emote tu memang padan',
  ],
  fi: [
    'moderaattorit nukkuvat taas',
    'laita ennusteet päälle',
    'tämä biisi on mahtava',
    'kamerasi on sumea',
    'montako meitä on täällä',
    'syön samalla illallista',
    'täällä sataa ulkona',
    'huomiseen kaikille',
    'hän on vihdoin takaisin',
    'tuo emote on täydellinen',
  ],
  no: [
    'moderatorene sover igjen',
    'skru på spådommene',
    'denne låten er skikkelig bra',
    'kameraet ditt er uskarpt',
    'hvor mange er her nå',
    'jeg spiser middag samtidig',
    'det regner her ute',
    'vi ses i morgen alle sammen',
    'han er endelig tilbake',
    'den emoten er perfekt',
  ],
  da: [
    'moderatorerne sover igen',
    'tænd for forudsigelserne',
    'den her sang er virkelig god',
    'dit kamera er sløret',
    'hvor mange er her nu',
    'jeg spiser aftensmad imens',
    'det regner herude',
    'vi ses i morgen alle sammen',
    'han er endelig tilbage',
    'den emote er perfekt',
  ],
  hu: [
    'a moderátorok megint alszanak',
    'kapcsold be a jóslatokat',
    'ez a szám nagyon jó',
    'a kamerád homályos',
    'hányan vagyunk itt',
    'közben vacsorázom',
    'itt kint esik az eső',
    'holnap találkozunk mindenkivel',
    'végre visszatért',
    'az az emote tökéletes',
  ],
  ca: [
    'els mods dormen altra vegada',
    'obre les prediccions',
    'aquesta cançó és boníssima',
    'la teva càmera es veu borrosa',
    'quanta gent hi ha ara',
    'estic sopant mentrestant',
    'aquí fora està plovent',
    'fins demà a tothom',
    'per fi ha tornat',
    'aquesta emoticona és perfecta',
  ],
  sl: [
    'moderatorji spet spijo',
    'vklopi napovedi',
    'ta pesem je odlična',
    'tvoja kamera je zamegljena',
    'koliko nas je tukaj',
    'medtem večerjam',
    'tukaj zunaj dežuje',
    'se vidimo jutri vsi',
    'končno se je vrnil',
    'ta emote je popoln',
  ],
  et: [
    'moderaatorid magavad jälle',
    'pane ennustused peale',
    'see lugu on väga hea',
    'sinu kaamera on udune',
    'mitu meid siin on',
    'söön samal ajal õhtust',
    'siin väljas sajab vihma',
    'homme näeme kõiki',
    'ta on lõpuks tagasi',
    'see emote on täiuslik',
  ],
  lt: [
    'moderatoriai vėl miega',
    'įjunk prognozes',
    'ši daina labai gera',
    'tavo kamera neryški',
    'kiek mūsų čia yra',
    'tuo pačiu vakarieniauju',
    'čia lauke lyja',
    'iki rytojaus visiems',
    'pagaliau jis grįžo',
    'tas emote tobulas',
  ],
  lv: [
    'moderatori atkal guļ',
    'ieslēdz prognozes',
    'šī dziesma ir lieliska',
    'tava kamera ir izplūdusi',
    'cik mūsu šeit ir',
    'tikmēr vakariņoju',
    'šeit ārā līst lietus',
    'uz rītdienu visiem',
    'beidzot viņš atgriezās',
    'tas emote ir ideāls',
  ],
  tl: [
    'tulog na naman ang mods',
    'buksan mo ang predictions',
    'ang ganda ng kantang ito',
    'malabo ang camera mo',
    'ilan tayo dito ngayon',
    'kumakain ako ng hapunan',
    'umuulan dito sa labas',
    'hanggang bukas sa inyong lahat',
    'nakabalik na siya sa wakas',
    'perpekto yung emote na yun',
  ],
};
